name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

variables:
  Configuration: 'Release'

trigger:
- master


steps:
- task: Npm@1
  displayName: Install
  inputs:
    command: install

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    customCommand: 'test'

- task: Npm@1
  displayName: Clean
  inputs:
    command: custom
    customCommand: 'run clean'

- task: Npm@1
  displayName: Compile
  inputs:
    command: custom
    customCommand: 'run compile'

- task: Bash@3
  inputs:
    targetType: inline
    script: 'git checkout -- package-lock.json'
# - task: Npm@1
#   displayName: Pack
#   inputs:
#     command: custom
#     customCommand: 'run pack-packages'

# - task: npmAuthenticate@0
#   inputs:
#     customEndpoint: https://pkgs.dev.azure.com/jbroekhuizen/_packaging/PrivateFeed/npm/registry/

# - task: Npm@1
#   displayName: publish
#   inputs:
#     command: custom
#     customCommand: 'publish-packages'
#     publishRegistry: useFeed
#     publishFeed: '8f9bd9e8-884b-45bf-bf27-f678c286d67a'

- task: Npm@1
  displayName: Publish
  inputs:
    command: custom
    customCommand: 'run publish-packages'


