name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

variables:
  Configuration: 'Release'

trigger:
- master


steps:
- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'

- task: Npm@1
  displayName: Install
  inputs:
    command: install

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    customCommand: 'test'

- task: Npm@1
  displayName: Clean
  inputs:
    command: custom
    customCommand: 'run clean'

- task: Npm@1
  displayName: Compile
  inputs:
    command: custom
    customCommand: 'run compile'

# - task: Bash@3
#   displayName: Git Reset
#   inputs:
#     targetType: inline
#     script: git reset --hard

- task: Npm@1
  displayName: Set Registry
  inputs:
    command: custom
    customCommand: config set registry https://pkgs.dev.azure.com/jbroekhuizen/_packaging/PrivateFeed/npm/registry/

- task: Npm@1
  displayName: Publish
  inputs:
    command: custom
    customCommand: 'run publish-packages'


