name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

variables:
  Configuration: 'Release'

trigger: none

pr:
- master

steps:
- task: Npm@1
  displayName: Install
  inputs:
    command: install

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml' 
  condition: always()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from **/coverage.cobertura.xml'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/**/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  condition: always()


- task: Npm@1
  displayName: Clean
  inputs:
    command: custom
    customCommand: 'run clean'

- task: Npm@1
  displayName: Compile
  inputs:
    command: custom
    customCommand: 'run compile'