name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604

variables:
  Configuration: 'Release'

trigger:
- master


steps:
- task: Bash@3
  displayName: Create npmrc file
  inputs:
    targetType: inline
    script: 'touch .npmrc && echo "registry=https://pkgs.dev.azure.com/jbroekhuizen/_packaging/PrivateFeed/npm/registry/" > .npmrc'

- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'

- task: Npm@1
  displayName: Install
  inputs:
    command: install

- task: Npm@1
  displayName: Test
  inputs:
    command: custom
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml' 

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'coverage/coberture-coverage.xml'


- task: Npm@1
  displayName: Clean
  inputs:
    command: custom
    customCommand: 'run clean'

- task: Npm@1
  displayName: Compile
  inputs:
    command: custom
    customCommand: 'run compile'

- task: Bash@3
  displayName: Git reset
  inputs:
    targetType: inline
    script: 'git reset --hard'

- task: Npm@1
  displayName: Publish
  inputs:
    command: custom
    customCommand: 'run publish-packages'


